### ISSUE TITLE
Klavioyo

### ISSUE THREAD

**Issue by jornwildenbeest** [FosterCommerce/klaviyoconnect#132]

**Comment by johnnynotsolucky** [comment]
Hi @jornwildenbeest, thank you for reporting this. 

Could you share the specific errors you saw and your Klaviyo config (without keys) that you used when you had these issues?

**Comment by jornwildenbeest** [comment]
Hi @johnnynotsolucky,

1. Just installed the plugin on a fresh craft 5 installation (with commerce installed).
2. Copied the craft commerce example templates folder to the root templates folder so you have something to work with.
3. Installed and enabled klaviyoconnect (so no config file used yet).
4. Tried to add a product to the cart.

I received the following error: 

```
2024-10-21 22:41:40 [web.ERROR] [KlaviyoAPI\ApiException] KlaviyoAPI\ApiException: [401] Client error: `POST https://a.klaviyo.com/api/events/` resulted in a `401 Unauthorized` response:
{"errors":[{"id":"a6f12b78-a0d8-423b-99f4-894e1ee668b1","status":401,"code":"not_authenticated","title":"Authentication  (truncated...)
 in /Users/jorn/Sites/craft-commerce-5/vendor/klaviyo/api/lib/API/EventsApi.php:155
Stack trace:
#0 /Users/jorn/Sites/craft-commerce-5/vendor/klaviyo/api/lib/API/EventsApi.php(132): KlaviyoAPI\API\EventsApi->createEventWithHttpInfo(Array, NULL)
#1 /Users/jorn/Sites/craft-commerce-5/vendor/klaviyo/api/lib/Subclient.php(61): KlaviyoAPI\API\EventsApi->createEvent(Array)
#2 /Users/jorn/Sites/craft-commerce-5/vendor/fostercommerce/klaviyoconnect/src/services/Api.php(63): KlaviyoAPI\Subclient->__call('createEvent', Array)
#3 /Users/jorn/Sites/craft-commerce-5/vendor/fostercommerce/klaviyoconnect/src/services/Track.php(230): fostercommerce\klaviyoconnect\services\Api->track('Updated Cart', Array, Object(fostercommerce\klaviyoconnect\models\EventProperties), NULL)
#4 /Users/jorn/Sites/craft-commerce-5/vendor/fostercommerce/klaviyoconnect/src/services/Track.php(76): fostercommerce\klaviyoconnect\services\Track->trackOrder('Updated Cart', Object(craft\commerce\elements\Order))
#5 /Users/jorn/Sites/craft-commerce-5/vendor/fostercommerce/klaviyoconnect/src/Plugin.php(81): fostercommerce\klaviyoconnect\services\Track->onCartUpdated(Object(craft\events\ModelEvent))
#6 [internal function]: fostercommerce\klaviyoconnect\Plugin::fostercommerce\klaviyoconnect\{closure}(Object(craft\events\ModelEvent))
#7 /Users/jorn/Sites/craft-commerce-5/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
#8 /Users/jorn/Sites/craft-commerce-5/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('craft\\commerce\\...', 'afterSave', Object(craft\events\ModelEvent))
#9 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/cms/src/base/Element.php(5875): yii\base\Component->trigger('afterSave', Object(craft\events\ModelEvent))
#10 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/commerce/src/elements/Order.php(2333): craft\base\Element->afterSave(true)
#11 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/cms/src/services/Elements.php(3784): craft\commerce\elements\Order->afterSave(true)
#12 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/cms/src/services/Elements.php(1221): craft\services\Elements->craft\services\{closure}()
#13 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/cms/src/services/Elements.php(3589): craft\services\Elements->ensureBulkOp(Object(Closure))
#14 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/cms/src/services/Elements.php(1307): craft\services\Elements->_saveElementInternal(Object(craft\commerce\elements\Order), false, false, NULL, Array, false, false, false)
#15 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/commerce/src/services/Carts.php(184): craft\services\Elements->saveElement(Object(craft\commerce\elements\Order), false)
#16 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/commerce/src/controllers/CartController.php(597): craft\commerce\services\Carts->getCart(true)
#17 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/commerce/src/controllers/CartController.php(139): craft\commerce\controllers\CartController->_getCart(true)
#18 [internal function]: craft\commerce\controllers\CartController->actionUpdateCart()
#19 /Users/jorn/Sites/craft-commerce-5/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /Users/jorn/Sites/craft-commerce-5/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /Users/jorn/Sites/craft-commerce-5/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('update-cart', Array)
#22 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('commerce/cart/u...', Array)
#23 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction('commerce/cart/u...', Array)
#24 /Users/jorn/Sites/craft-commerce-5/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#25 /Users/jorn/Sites/craft-commerce-5/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /Users/jorn/Sites/craft-commerce-5/web/index.php(12): yii\base\Application->run()
#27 /Users/jorn/.composer/vendor/laravel/valet/server.php(110): require('/Users/jorn/Sit...')
#28 {main} {"memory":36154592,"exception":"[object] (KlaviyoAPI\\ApiException(code: 401): [401] Client error: `POST https://a.klaviyo.com/api/events/` resulted in a `401 Unauthorized` response:
{\"errors\":[{\"id\":\"a6f12b78-a0d8-423b-99f4-894e1ee668b1\",\"status\":401,\"code\":\"not_authenticated\",\"title\":\"Authentication  (truncated...)
 at /Users/jorn/Sites/craft-commerce-5/vendor/klaviyo/api/lib/API/EventsApi.php:155)"} 
```

But I've just noticed the try and catch in the trackService for example https://github.com/FosterCommerce/klaviyoconnect/blob/main/src/services/Track.php#L220

Does this also catches the error when for some reasong klaviyo returns an error or goes offline?
