### ISSUE TITLE
Unknown Property on Save User

### ISSUE THREAD

**Issue by RitterKnightCreative** [FosterCommerce/klaviyoconnect#4]
Upon saving or creating a new user, getting an error:

``Getting unknown property: craft\events\ModelEvent::params``

Stack Trace:
```
yii\base\UnknownPropertyException: Getting unknown property: craft\events\ModelEvent::params in /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/yiisoft/yii2/base/BaseObject.php:141
Stack trace:
#0 /Volumes/ProBeast/Users/dave/Sites/Jale/site/plugins/klaviyoconnect/src/services/Events.php(18): yii\base\BaseObject->__get('params')
#1 /Volumes/ProBeast/Users/dave/Sites/Jale/site/plugins/klaviyoconnect/src/Plugin.php(34): fostercommerce\klaviyoconnect\services\Events->onSaveUser(Object(craft\events\ModelEvent))
#2 [internal function]: fostercommerce\klaviyoconnect\Plugin->fostercommerce\klaviyoconnect\{closure}(Object(craft\events\ModelEvent))
#3 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
#4 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\elements\\...', 'afterSave', Object(craft\events\ModelEvent))
#5 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/craftcms/cms/src/base/Element.php(1846): yii\base\Component->trigger('afterSave', Object(craft\events\ModelEvent))
#6 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/craftcms/cms/src/elements/User.php(1314): craft\base\Element->afterSave(false)
#7 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/craftcms/cms/src/services/Elements.php(490): craft\elements\User->afterSave(false)
#8 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/craftcms/cms/src/controllers/UsersController.php(1037): craft\services\Elements->saveElement(Object(craft\elements\User), false)
#9 [internal function]: craft\controllers\UsersController->actionSaveUser()
#10 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-user', Array)
#13 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-user', Array)
#14 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('users/save-user', Array)
#15 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/craftcms/cms/src/web/Application.php(541): craft\web\Application->runAction('users/save-user', Array)
#16 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /Volumes/ProBeast/Users/dave/Sites/Jale/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Volumes/ProBeast/Users/dave/Sites/Jale/site/public_html/index.php(21): yii\base\Application->run()
#19 {main}

**Comment by sjcallender** [comment]
Fixed in version 2.0.1
